virt-s1/rhel-edge

check-ostree.yaml
tasks/check-greenboot.yml

Since ocp 3.11 will be deprecated, file server has been moved to ocp 4.6. The greenboot-failing-unit rpm package URL should be updated as well

Update greenboot-failing-unit-1.0-1.el8.noarch.rpm download URL

---

ostree-ng.sh
ostree.sh

PSI openstack vm does not have firewalld installed, disabling firewalld is not required.

Disable firewalld to make ostree repo happy

---

ostree.sh

Before the httpboot option, the virt-install was enabling the console, which is very useful for debuging.
The remote uefi boot doesn't support the option 'extra-args', so it was removed. But it can be activated at the Grub entry.

Add back the console=ttyS0 to the httpboot installer

---

setup.sh

localectl set-locale LANG=en_US.UTF-8 on RHEL 9.1 will report "Failed to issue method call: Interactive authentication required." error

Fix localectl set-locale error issue

---

ostree.sh

Folder isolinux is not required by http boot

Do not download isolinux folder for http boot

---

ostree-ng.sh
ostree-raw-image.sh
ostree-simplified-installer.sh
ostree.sh

RHEL 8.5 will not be supported by CI and weldr-client will replace composer-cli since RHEL 8.6

Remove composer-cli support

---

check-ostree.yaml
ostree-ng.sh
ostree.sh

This PR will updates downstream code to test container image embedding in OSTree commits when this feature is released on RHEL 8.7, 9.1, CS8, and CS9.

Embedding container image into image

---

ostree-ng.sh

This PR updates edge-installer to support Fedora 36.

Update edge-installer to support Fedora 36

---

check-ostree.yaml
ostree-raw-image.sh
ostree-simplified-installer.sh

Update test to support new change - mount /sysroot as ro for raw image and simplified installer.

Update test to support mount /sysroot as ro on raw image and simplified installer on RHEL 9.2 and 8.8

---

ostree-raw-image.sh
ostree-simplified-installer.sh

PR https://github.com/osbuild/osbuild-composer/pull/3276 changed /sysroot to RO on RHEL 8.8 and CS8

osbuild-composer v75 revert /sysroot to RO on RHEL 8.8 and CS8

---

check-ostree.yaml
ostree-ng.sh
ostree.sh

This pull request includes another embedded container in edge-commit and edge-installer blueprints, just like container-embedding.sh upstream test case.
Playbook tasks have been included to check the fedora minimal container image is embedded, and the image is not being pulled again (task fails if podman try to pull latest tag).

Test fedora minimal embedded container in downstream

---

arm-commit.sh
arm-installer.sh
check-ostree.yaml

This PR includes the Fedora embedded container image for aarch64 architecture in edge-commit and edge-installer tests.
The container image was previously uploaded to the Gitlab Container Registry of our project rhel-edge.

Add Fedora aarch64 embedded container image

---

ostree-fdo-container.sh

script timeout in 300 seconds if fdouser is not created, now extend it to 600 seconds to avoid failure.

add more wait time until fdouser present

---

ostree-ng.sh

Found same bug https://bugzilla.redhat.com/show_bug.cgi?id=2124239 on RHEL 8.9 for edge-installer for http boot. This PR includes workaround for RHEL 8.9.

Workaround bug BZ#2124239 on RHEL 8.9 for edge-installer for http boot

---

check-ostree.yaml

Issue is that system sometimes reboots before the SSH connection closes, and the host gets marked as unreachable
Set pre_reboot_delay to 60 to workaround this issue

Add workaround for reboot issue

---

.github/workflows/rhel-8-6.yml
.github/workflows/rhel-8-7.yml
.github/workflows/rhel-8-8.yml
.github/workflows/rhel-8-9.yml

This PR includes a missing parenthesis to fix errors such as:
```
[virt-s1/rhel-edge] Run failed at startup: Run Edge Test on RHEL 8.8 - main (f018d78)
Invalid workflow file: .github/workflows/rhel-8-8.yml#L11
The workflow is not valid. .github/workflows/rhel-8-8.yml (Line: 11, Col: 9): Unexpected end of expression: ')'. Located at position 340 within expression: github.event.issue.pull_request && (endsWith(github.event.comment.body, '/test-rhel-8-8') || endsWith(github.event.comment.body, '/test-rhel-8-8-virt') || endsWith(github.event.comment.body, '/test-rhel-8-8-ng') || endsWith(github.event.comment.body, '/test-rhel-8-8-raw') || endsWith(github.event.comment.body, '/test-rhel-8-8-simplified')
```

Fix syntax parenthesis in Github Actions Workflows

---

arm-commit.sh
arm-ignition.sh
arm-installer.sh
arm-minimal.sh
arm-raw.sh
arm-simplified.sh
minimal-raw.sh
ostree-8-to-9.sh
ostree-9-to-9.sh
ostree-ignition.sh
ostree-ng.sh
ostree-raw-image.sh
ostree-simplified-installer.sh
ostree.sh

We have seen in previous downstream CI tests, a flaky issue with podman when running Ansible playbook from container.
This PR proposes a possible workaround to issue [Issue 3478](https://github.com/virt-s1/rhel-edge/issues/3478),  to make sure podman "grants the user in the container access to the same groups as the user on the host" [[1]](https://access.redhat.com/solutions/6985126). Thus, avoiding "lsetxattr: operation not permitted".

Add workaround for podman lsetxattr flaky issue

---

ostree-ami-image.sh

Now that nightly repo has osbuild-composer-85-1.el9.x86_64.rpm included, osbuild-composer is able to generate an edge AMI that can be uploaded and deployed on AWS. It would be useful to include a dedicated test script for automation in downstream.
ostree-ami-image.sh uses osbuild-composer to build edge-ami image type, upload it to a S3 bucket and deploy an EC2 instance using that image.
Support to aarch64 has been included.

Include test for edge-ami image type

---

.github/workflows/cleanup-aws-ami.yaml
tools/aws-ami-cleanup.sh

This PR cleans some of the idle AWS service elements in the AWS Default Region.
`aws-ami-cleanup.sh` script searches and removes buckets, images, snapshots, and key pairs that have been created more than 4 hours ago at the workflow triggering moment.
`cleanup-aws-ami.yaml` workflow allows both manual and scheduled triggering of the script (every four hours).

ci: add aws edge-ami cleanup job

---

tools/aws-ami-cleanup.sh

When there is no buckets created by our rhel-edge-ci or composer-ci, the awscli command `aws s3 ls` fails. Therefore we should ignore this error in order to continue the execution of the script.

ci: fix aws ami cleanup bucket list error

---

.github/workflows/cleanup-aws-ami.yaml

I have seen the ami cleanup workflow being triggered in my fork repo. The workflow fails due to AWS credentials issue, and is not even meant to be run on fork repos.
This PR avoids ami cleanup job from running on any fork repos.

ci: do not run ami cleanup job on any fork repos

---

check-ostree.yaml

This is a suggested workaround for issue https://github.com/virt-s1/rhel-edge/issues/5955

check dmesg with privileges to avoid read kernel buffer failure

---

ostree-ng.sh

This is a suggested workaround to solve issue https://github.com/virt-s1/rhel-edge/issues/6772

test: update ostree ref and ansible os name variables iot-installer-f38

---

ostree-ng.sh

Suggested workaround for a similar issue described at https://github.com/virt-s1/rhel-edge/issues/6772, but this time iot-installer-f39 and iot-installer-rawhide.

test: update variables in iot-installer f39 and f40

---

.github/workflows/arm-fedora-39.yml
.github/workflows/trigger-arm-fedora.yaml

Since we have disabled fedora-38, there are aarch64 workflow jobs that need to be updated.

ci: update arm tests from fedora-38 to fedora-39

---

minimal-raw.sh

We need to update `MINIMAL_RAW_FILENAME` and  `MINIMAL_RAW_DECOMPRESSED` variables values in Fedora systems.

test: update minimal raw file name variables in Fedora systems

---

ostree-ami-image.sh

We need to remove residual configuration line from edge-ami-image test case.

test: remove residual configuration from edge-ami-image test case

---

ostree-ng.sh

ANSIBLE_OS_NAME variable value has changed from rhel to rhel-edge in edge installer test case RHEL-9.5, we need to update this variable.

test: fix ansible os name variable in edge installer

---

.github/workflows/rhel-8-10.yml
.github/workflows/rhel-8-8.yml
.github/workflows/rhel-9-4.yml
tmt/plans/edge-test.fmf

I have tried these conditions but do not work:
1. - when: distro==rhel and version == 8.10    (tmt_context: "arch=x86_64;distro=rhel;version=8.10")
2. - when: distro==rhel and version == 810     (tmt_context: "arch=x86_64;distro=rhel;version=810")
3. - when: distro==rhel and version == "810"  (tmt_context: "arch=x86_64;distro=rhel;version=810")
so I removed version from github workflow file, and only use distro, it works now.
1. - when: distro == rhel-8-10   (tmt_context: "arch=x86_64;distro=rhel-8-10")
Please let me know if you know how to fix it and we can add version back.

ci: disable cases in rhel8

---

ostree-fdo-db.sh

In testing-farm machine, cargo install failed because diesel_cli 2.2.0 requires  rustc 1.78.0 or newer. Didn't see this error before, probably diesel_cli has a new version now.
As I cannot upgrade rustc to 1.78 on this machine, change to old version 2.1.1 can resolve this issue.
[root@3482cc1f-759a-497b-a104-32c635b71238 ~]# cargo install --force diesel_cli --no-default-features --features sqlite
Updating crates.io index
error: cannot install package `diesel_cli 2.2.0`, it requires rustc 1.78.0 or newer, while the currently active rustc version is 1.75.0
`diesel_cli 2.1.1` supports rustc 1.65.0

ci: fix fdo db case failures on rhel9.4

---

ostree-ami-image.sh
ostree-fdo-aio.sh
ostree-fdo-db.sh
ostree-ng.sh
ostree-raw-image.sh
ostree-simplified-installer.sh
ostree-vsphere.sh

We have seen in our downstream CI several failed tests due to inconsistency of os name (or ansible os name) variable across distros. Thus, playbook tasks such as find /var /mnt mount points failed.
This PR configures mentioned variable value to `rhel-edge` only when test are perfomed by RHEL-9.5, centos-stream-9. In addition edge-commit will also have `rhel-edge` variable value across all distros under test.

test: adjust os name variable in test cases

---

ostree-ng.sh
setup.sh

Disable Openshift in edge-installer due to issue https://github.com/virt-s1/rhel-edge/issues/7544

test: disable openshift in edge-installer

---

minimal-raw.sh

Following rhel-9.4 tests are failing:
https://artifacts.osci.redhat.com/testing-farm/91e03f1f-df69-4cfe-8abe-ac1a52611e5e/work-edge-arm-minimalepiqi6tx/tmt/plans/edge-test/edge-arm-minimal/execute/data/guest/default-0/tmt/tests/edge-test-1/output.txt
https://artifacts.osci.redhat.com/testing-farm/aaee6ea8-384a-4309-b776-50d61800bf39/work-edge-x86-minimalgd6vl8mj/tmt/plans/edge-test/edge-x86-minimal/execute/data/guest/default-0/tmt/tests/edge-test-1/output.txt
We should use proper minimal image name in rhel-9.4.

test: update minimal image name in rhel-9.4

---

ostree-ng.sh

Let's increase RAM size of httpboot VM in edge-installer for all distros.

test: edge-installer increase httpboot ram vm for all distros

---

tmt/plans/edge-test.fmf

Following Xiaofeng's suggestion, let's increase some processor and memory resources allocated to testing-farm machines to try to circumvent issue https://issues.redhat.com/browse/TFT-2699

ci: increase testing-farm processor and memory resources

---

.github/workflows/fedora-rawhide.yml
.github/workflows/trigger-fedora.yml
arm-commit.sh
arm-ignition.sh
arm-installer.sh
arm-minimal.sh
arm-raw.sh
arm-rebase.sh
arm-simplified.sh
minimal-raw.sh
ostree-ng.sh
ostree-raw-image.sh
ostree.sh

Moving fedora-rawhide workflow job to testing-farm.

ci: moving fedora-rawhide workflow job to testing-farm

---

.github/workflows/fdo-container.yml

We need to update fdo container compose name to proper name according to https://api.testing-farm.io/v0.1/composes/redhat

ci: update fdo container compose name

---

.github/workflows/fdo-container.yml

The fdo container workflow jobs are not being triggered due to the following error:
```
Invalid workflow file: .github/workflows/fdo-container.yml#L47
The workflow is not valid. .github/workflows/fdo-container.yml (Line: 47, Col: 22): Job 'fdo-container-community' depends on unknown job 'pre-fdo-container-community'. .github/workflows/fdo-container.yml (Line: 78, Col: 22): Job 'fdo-container-official' depends on unknown job 'pre-fdo-container-official'.
```
In order to fix it, we need to delete the unknown job 'pre-fdo-container-official'.

ci: fix fdo container workflow job dependency

---

.github/workflows/centos-stream-9.yml
.github/workflows/fedora-39.yml
.github/workflows/fedora-40.yml
.github/workflows/fedora-rawhide.yml
.github/workflows/rhel-8-8.yml
.github/workflows/rhel-9-4.yml
.github/workflows/rhel-9-5.yml

We need to update testing-farm-as-github-action version to https://github.com/sclorg/testing-farm-as-github-action/releases/tag/v3.1.0
Some bugs have been fixed, such as https://github.com/sclorg/testing-farm-as-github-action/issues/209

ci: update testing-farm-as-github-action version

---

.github/workflows/fdo-container.yml

FDO container workflows are being triggered twice. In order to fix this another condition has to be included for each job.

ci: update fdo container workflows condition

---

.github/workflows/fdo-container.yml

We need to update the compose from rhel-9.4 to rhel-9.5 of the ostree fdo official container test.

ci: update fdo official container test compose to rhel-9.5

---

.github/workflows/fedora-40.yml
.github/workflows/fedora-41.yml
.github/workflows/fedora-rawhide.yml
.github/workflows/rhel-8-8.yml
.github/workflows/rhel-9-4.yml
.github/workflows/rhel-9-5.yml

In order to solve testing-farm issue https://github.com/sclorg/testing-farm-as-github-action/issues/209 that our CI has seen several times, we need to update our workflow jobs to use testing-farm-as-github-action v3.1.2

ci: update testing-farm-as-github-action to v3.1.2

---

.github/workflows/fdo-container.yml

current fdo container tests have pull request status names that is not clear to tell us what's being tested.

ci: fix fdo container tmt status name

---

.github/workflows/trigger-fdo-container.yml

FDO container test trigger jobs are failing due to:
`Error: Missing either 'issue-number' or 'comment-id'.`
Check https://github.com/virt-s1/rhel-edge/actions/runs/12065220907/job/33643538622
We need to verify if this is fixed by updating versions of `peter-evans/create-pull-request `and `peter-evans/create-or-update-comment`

ci: update fdo container trigger create pr and comment versions

---

fdo-container.run

This is a suggested workaround for https://github.com/virt-s1/rhel-edge/issues/8999

ci: remove fdo-container.run file to trigger fdo container workflows properly

---

fdo-container.run

Remove fdo-container file to fix container ci trigger.

ci: remove fdo-container file to fix container ci trigger

---

tmt/plans/edge-test.fmf

CI runs on testing-farm, but often found that testing-farm job is cancelled, because we have lots of testing-farm job running in CI, disable these two low priority test cases to reduce the testing-farm workload.
1. test case edge-x86-pulp : this test case is to push edge commit files into a pulp server, and then pull it from pulp server. Never heard of any pulp issue since this test case created, and pulp is not part of RHEL for Edge project, so consider this pulp test case as low priority.
2. test case edge-x86-fdo-aio: this test case is to setup fdo-aio server and then build and provision edge vm with it. As fdo function tests are already covered in other test cases, and fdo-aio is more likely a developer tool, and customer will not use it, so consider this fdo-aio test case as low …

ci:remove some test cases

---

.github/workflows/trigger-fedora.yml
tmt/plans/edge-test.fmf

To reduce testing-farm workload, disable F41 and F42 for now. As fedora is upstream of Centos-Stream and RHEL, we can only focus on Fedora rawhide, which is 43 now.

ci: disable f41 and f42

---

check-ostree.yaml
ostree-ng.sh
ostree.sh

The fedora-minimal:latest embedded container digests have been updated. Those digest were previously hard-coded. Therefore edge-commit, and edge-installer test cases were failing.
This modification is based on upstream commit https://github.com/osbuild/osbuild-composer/commit/68a75b086b0d79c40b07051c4f8a7e0d808b31fc, tries to determine all the values dynamically. 
This is a suggested fix for issues https://github.com/virt-s1/rhel-edge/issues/10567 and https://github.com/virt-s1/rhel-edge/issues/10590

test: update edge-commit and edge-installer embedded container image
