virt-s1/rhel-edge

- .gitignore
- kitebot/Jenkinsfile
- scripts/provision.sh
> add rhel 8.4 ng test

- README.md
- kitebot/Jenkinsfile
- tasks/build-ostree-image.yml
1. Jenkinsfile: Remove EL 8.3 Bare tests
2. Update build-ostree-image.yml to fix "RHSM secrets not found on host"
3. Update README.md for new changes
> Some updates:

- files/provision.sh
- tasks/build-ostree-image.yml
In case of something changed, both of them are added
> RHEL 8.4 is in beta, rhel-8-beta.json needs update to rhel-8.json

- kitebot/Jenkinsfile
- ostree-bare-ng.yml
- tasks/build-ostree-image-ng.yml
- tasks/build-upgrade-image-ng.yml
- tasks/check-ostree-bare-ng.yml
- tasks/deploy-openstack.yml
- templates/container.j2
- templates/upgrade-container.j2
add 8.4 ng testcase in downstream
> add 8.4 bare ng test

- ostree-ng.sh
- ostree.sh
To work with more environments, let's install firewalld, enable it. And move libvirt integration network into trusted zone
> Install firewalld and install libvirt integration network into trusted zone

- ostree-ng.sh
- ostree.sh
There was an error at the BIOS VM clean up, it was checking for the UEFI VM instead f the BIOS one.
> Fix BIOS VM clean and other improvements

- check-ostree.yaml
- kitebot/Jenkinsfile
- ostree-raw-image.sh
- ostree-simplified-installer.sh
Added two test cases:
1. test edge-raw-image
2. test edge-simplified-installer
> add test case for raw-image and simplified-installer

- check-ostree.yaml
- ostree-raw-image.sh
- ostree-simplified-installer.sh
1. [ostree name and ref are pre-defined in raw and simplified in new](https://github.com/virt-s1/rhel-edge/commit/00bda7af6e2c51b3c42c46e58ff4df04fed1f9f7)
2. [Filter non-error and non-failed dmesg log](https://github.com/virt-s1/rhel-edge/commit/439cc7b3c1368c90671d09c0fde60fc24143f8dd)
> Support new features on RHEL 9

- check-ostree.yaml
- ostree-simplified-installer.sh
- ostree.sh
Since RHEL 8.6 and 9.0, raw image and simplified installer will have disk encrypted by default, simplified installer will use FDO by default
> Add FDO and disk encryption support

- check-ostree.yaml
- ostree-simplified-installer.sh
- setup.sh
- tools/mock_source.sh
1. Add fdo onbaording device "/boot/device-credentials" checking
2. Work around a podman bug in CS8
3. Add mock_sourch.sh to help create 3rd party repo and add source
> Add fdo onbaording device "/boot/device-credentials" checking and work around podman bug

- HELP.md
- setup.sh
Pull request to include in the setup.sh script the code lines that verify proper file permissions of ostree_key.
> setup:ostree_key permission check added to setup.sh

- ostree-ng.sh
- ostree-raw-image.sh
- ostree.sh
Update test to install package sssd in all edge images for regression due to bug [BZ#2088459](https://bugzilla.redhat.com/show_bug.cgi?id=2088459)
> Install package sssd in all edge images for BZ#2088459

- ostree-ng.sh
https://github.com/virt-s1/rhel-edge/issues/155
> Disable BIOS installation test on ostree-ng.sh due to issue #155

- ostree-ng.sh
PR to update ostree-ng.sh to support auto pushing to container registry.
> Update ostree-ng.sh to support auto pushing to container registry

- check-ostree.yaml
This pull request fix the default value of embedded container variable.
> Fix embedded container variable typo

- check-ostree.yaml
- ostree-simplified-installer.sh
> replace containerized fdo with all-in-one service

- ostree-simplified-installer.sh
Fix simplified installer failure issue due to new defination. It's changed by PR https://github.com/osbuild/osbuild-composer/pull/3166.
> Fix simplified installer failure issue due to new defination

- README.md
- build-image.yaml
- check-ostree.yaml
- simplified-arm.sh
- tools/deploy_arm_bare.sh
edge-simplified-installer has an issue #1662 on RHEL 8.8 and CS8.
Test result on bare metal ARM server:
- RHEL -9.2: PASS
- CS9: PASS
- RHEL -8.8: FAIL
- CS8: FAIL
> Add edge-simplified-installer image test for ARM

- README.md
- build-image.yaml
- rebase-arm.sh
Test has been running on aarch64 bare metal server. Passed on RHEL 8.8/9.2, CentOS Stream 8/9, Fedora 37/rawhide.
> Add rebase test for ARM

- check-ostree.yaml
We have same bugs on bugzilla already and they can't be fixed soon, a workaround should be added to run the rest of tests
> Workaround for issue#1893

- build-image.yaml
- edge-raw.sh
- tools/deploy_arm_bare.sh
- tools/user-data.arch.87
- tools/user-data.arch.88
- tools/user-data.arch.91
- tools/user-data.arch.92
Building image on a standalone VM and installation on another VM
> New arch to drive raw image test

- ostree-ng.sh
This PR updates edge-installer with a new HTTP boot VM included just before UEFI VM creation.
> Include http boot vm in edge-installer

- .github/workflows/centos-stream-9.yml
- .github/workflows/rhel-9-2.yml
- check-ostree.yaml
- ostree-ignition.sh
Ignition on raw image and simplified instaler test on RHEL 9.2 and CS9
- customizations.ignition.firstboot
- customizations.ignition.embedded
Since [osbuild-composer v74](https://github.com/osbuild/osbuild-composer/releases/tag/v74) has not been released on RHEL 9.2 and CS9 repo. Raw image part of test is commented out for now.
> Add ignition test

- .github/workflows/trigger-8.yml
- .github/workflows/trigger-9.yml
- .github/workflows/trigger-adds-on.yml
- .github/workflows/trigger-cs.yml
- .github/workflows/trigger-fedora.yml
- .github/workflows/trigger-package.yml
Update to latest version to fix set-output deprecate warnning
> workflow: Update all peter-evans's actions

- check-ostree.yaml
This PR includes a playbook task that executes the sos report and make sure command execution has been successful.
Needs osbuild-composer v74.
> Check sos package has been included in the edge commit package set

- check-ostree.yaml
Add restriction for RHEL 9.2, 8.8 and above
> Fix sos package checking task

- check-ostree.yaml
This is a suggested workaround for https://github.com/virt-s1/rhel-edge/issues/2424
> Workaround issue #2424

- ostree.sh
The old repo URL does not work anymore
> Update fedora repo URL for ostree.sh

- .github/workflows/arm-centos-stream-9.yml
- .github/workflows/trigger-arm-cs9.yml
1. remove "(" in arm-centos-stream-9.yml
2. Do not check cs9 compose file, because it will run as schedule
> workflow: Fix arm cs9 workflow issue

- .github/workflows/fdo-container.yml
- data/fdo/manufacturing-server.yml
- data/fdo/owner-onboarding-server.yml
- data/fdo/rendezvous-server.yml
- data/fdo/serviceinfo-api-server.yml
- ostree-fdo-container.sh
Added fdo aio container test in downstream:
1. only run on rhel9.2, as container works in the same way on all os
2. only run once a week.
> add fdo container test

- ostree-fdo-container.sh
The root reason of failure is here:
tee fdo/fdouser > /dev/null << EOF
fdouser ALL=(ALL) NOPASSWD: ALL
EOF
tee: fdo/fdouser: Permission denied
Changed to:
sudo tee fdo/fdouser > /dev/null << EOF
fdouser ALL=(ALL) NOPASSWD: ALL
EOF
Should resolve this failure.
> fix fdo container failure

- .github/workflows/centos-stream-8.yml
- .github/workflows/centos-stream-9.yml
- .github/workflows/fdo-container.yml
- .github/workflows/fedora-37.yml
- .github/workflows/fedora-38.yml
- .github/workflows/fedora-rawhide.yml
Only installer test uses large GCP instance due to CRC
> workflow: Use medium size GCP instance to run test

- ostree-fdo-container.sh
Use this function to check fdouser
wait_for_fdo () {
SSH_STATUS=$(sudo ssh "${SSH_OPTIONS[@]}" -i "${SSH_KEY}" admin@"${1}" "id -u fdouser > /dev/null 2>&1 && echo -n READY")
if [[ $SSH_STATUS == READY ]]; then
echo 1
else
echo 0
fi
}
> fix fdo container test failure

- .github/workflows/fedora-37.yml
- .github/workflows/fedora-38.yml
- .github/workflows/fedora-rawhide.yml
- ostree-ng.sh
Use Github secret instead of copying file into runner
> Fedora rawhide runner does not have crc pull secret file copied

- README.md
Update README file Test Run for x86_64 ignition.
> Add Test Run comment for x86_64 ignition

- .github/workflows/centos-stream-8.yml
- .github/workflows/centos-stream-9.yml
- .github/workflows/fedora-37.yml
- .github/workflows/fedora-38.yml
- .github/workflows/fedora-rawhide.yml
for container image ocp4 running test
> workflow: run ostree-ng.sh on rhos-01 for all distros

- ostree-ng.sh
don't use crc on cs and fedora test, but use ocp4 instead
> remove crc from ostree-ng.sh

- build-image.yaml
- ostree-simplified-installer.sh
Workaround issue https://bugzilla.redhat.com/show_bug.cgi?id=2026795#c24
> test: Change the fdouser file location to /etc/fdo

- ostree-ng.sh
- ostree-raw-image.sh
- ostree.sh
systemd bug has been fixed, libvirtd workaround can be removed
> test: remove libvirtd workaround

- ostree-simplified-installer.sh
workaround bug https://bugzilla.redhat.com/show_bug.cgi?id=2026795
> test: disable selinux for simplified installer test as a workaround

- .github/workflows/centos-stream-9.yml
- .github/workflows/rhel-9-3.yml
This PR includes workflow jobs to trigger edge-ami CI tests in RHEL-9.3 and CS9.
> Add edge-ami workflow jobs in RHEL-9.3 and CS9

- check-ostree.yaml
- ostree-vsphere.sh
Passed on local rhel9.3 and cs9.
> add vmdk test case

- .github/workflows/trigger-fedora.yml
osbuild-composer does not support fedora 40 and no Modular folder in fedora 39 repo
> ci: disable fedora 39 and rawhide test

- ostree-ami-image.sh
Do not need intermediate file to get value.
> Wait running

- ostree-vsphere.sh
1. disable test on datacenter 6.7
2. change datacenter 7.0 test to bos lab server
> use one bos lab server

- .github/workflows/centos-stream-9.yml
- .github/workflows/fedora-39.yml
- .github/workflows/rhel-9-3.yml
Extend arm minimal test to 90 seconds.
> ci: fix https://github.com/virt-s1/rhel-edge/issues/4819

- check-minimal.yaml
> test: enable persistent log on Fedora 39 for ARM

- tools/aws-ami-cleanup.sh
This PR terminates AWS EC2 instances that have 4 or more hours running on AWS default region.
The code is able to terminate both downstream and upstream instances making use of the tags `rhel-edge-ci` and `composer-ci` correspondingly.
> ci: terminate AWS EC2 idle instances

- .github/workflows/cleanup-vsphere.yaml
Do not run this job on any fork repos.
> ci: run vsphere cleanup in main branch

- tools/aws-ami-cleanup.sh
Before submitting this PR, the script failed to continue its execution whenever a failure happened in a particular idle resource.
For example, the script failed to remove an idle snapshot that depended on an ami image (that did not have tags). Therefore, the script failed to remove the rest of idle resources.
This PR tries to circumvent this issue ignoring if an error occurs during particular idle resource deletion.
> ci: continue removing idle resources in case of failure

- .github/workflows/fedora-39.yml
Add test workflow for iot-simplified-installer on f39
> ci: add iot-simplified test case workflow

- ostree-pulp.sh
added pulp child commit upload test case as bug https://github.com/pulp/pulp_ostree/issues/289 fixed.
> test: add pulp child commit upload test case

- ostree-simplified-installer.sh
This PR is a suggested workaround for https://github.com/virt-s1/rhel-edge/issues/5958
> test: update ostree_ref of fedora during upgrade image building

- ostree-simplified-installer.sh
Workaround of issue 'pip3 install yq' on RHEL 8.8 and 8.6. [litian]
> Workaround of issue 'pip3 install yq' on RHEL 8.8 and 8.6. [litian]

- check-minimal.yaml
- minimal-raw.sh
The fix requires 1. qcow2 be expanded to 8G; 2. growpart and resize2fs in guest.
> fix: expand disk to 8G for Fedora 39+ arm-minimal test. [litian]

- .github/workflows/fedora-39.yml
- tmt/plans/edge-test.fmf
Moving fedora-39 workflow job to testing-farm
> ci: moving fedora-39 workflow job to testing-farm

- minimal-raw.sh
This is a suggested workaround for https://github.com/virt-s1/rhel-edge/issues/7752
> test: update minimal raw variables in rhel-9.5

- check-minimal.yaml
This PR fixes https://github.com/virt-s1/rhel-edge/issues/7789
> test: add RHEL-9.5 repos to check-minimal playbook

- .github/workflows/trigger-9.yml
This PR disables RHEL-9.0 workflow job from CI.
> ci: disable rhel-9.0 workflow job

- .github/workflows/trigger-cs.yml
This PR cleans up trigger cs yaml file to remove CS8 comments.
> ci: cleanup trigger centos-stream-8

- minimal-raw.sh
- ostree-ng.sh
- ostree-raw-image.sh
- ostree-simplified-installer.sh
- ostree.sh
podman ansible container need --network=host to reach target vm on rhel8.10 and rhel8.6 testing-farm machine.
> ci: fix ansible container issue on rhel8 testing-farm machine

- .github/workflows/fedora-39.yml
- .github/workflows/fedora-40.yml
Moving fedora-40 workflow job to testing-farm.
> ci: moving fedora-40 workflow job to testing-farm

- README.md
Reverts virt-s1/rhel-edge#7915
> Revert "ci: test rhel 8.8 and 8.10"

- ostree-ng.sh
This is a suggested workaround for https://issues.redhat.com/browse/RHEL-41024
> test: increase RAM of httpboot vm to fix RHEL-41024

- ostree-vsphere.sh
vmdk test failed, and asked vsphere team that they have changed the group from Automation to Edge ,so update our test case as well.
> fix: vsphere host changed

- check-ostree.yaml
This is a suggested workaround for https://github.com/virt-s1/rhel-edge/issues/8031
> test: fix boot-complete.target issue#8031

- setup.sh
Add rawhide repositories in setup.
> test: add rawhide repositories in setup

- .github/workflows/fdo-container.yml
- tmt/plans/edge-test.fmf
- tmt/tests/test.sh
Moving fdo official container and community container workflow jobs to testing-farm.
> ci: moving fdo container workflow jobs to testing-farm

- tmt/plans/edge-test.fmf
> ci: fix tmt plan missing colons

- .github/workflows/fdo-container.yml
Remove unnecessary steps from fdo container workflow jobs.
> ci: remove unnecessary steps from fdo container workflow jobs

- .github/workflows/fdo-container.yml
Remove unnecessary in-progress steps from fdo container workflow jobs.
> ci: remove unnecessary in-progress steps from fdo container workflow

- .github/workflows/trigger-adds-on.yml
Disable temporarily fapolicyd and grafana-pcp adds-on workflow jobs.
> ci: disable temporarily fapolicyd and grafana-pcp adds-on workflow jobs

- .github/workflows/fdo-container.yml
Fix syntax fdo container workflow jobs
> ci: fix syntax fdo container workflow jobs

- tmt/tests/edge-test.fmf
> ci: increase test duration

- tmt/tests/edge-test.fmf
Increase test duration in minutes.
> ci: increase test duration in minutes

- tmt/tests/edge-test.fmf
Decrease test duration due to TF issue.
> ci: decrease test duration due to TF issue

- ostree.sh
This is a suggested workaround for issue https://github.com/virt-s1/rhel-edge/issues/9968
> test: update edge-commit-cs9 grub default menu entry

- check-ostree-iot.yaml
- iot-installer.sh
- iot-setup.sh
- iot-simplified-installer.sh
- tmt/plans/iot-test.fmf
- tmt/tests/iot-test.fmf
- tmt/tests/test.sh
This PR includes:
1. automation test script for fedora-iot installer ISO image.
2. automation test script for fedora-iot simplified-installer ISO image.
3. automation test script to setup CI environment.
4. testing-farm and tmt configuration files.
This PR does not include CI workflow files, a follow-up PR will be created to setup CI workflow to trigger the test scripts.
> ci: add test script of installer and simplified-installer

- check-ostree-iot.yaml
> ci: fix iot playbook syntax
